# Generated by Django 4.1.3 on 2022-11-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["content"]},
        ),
    ]
